# Generated by Django 3.2 on 2023-01-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=300, verbose_name='First name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last name')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('undisclosed ', 'Undisclosed')], max_length=300, null=True, verbose_name='Gender')),
                ('organisation', models.CharField(choices=[('Norwegian Institute for Water Research ', 'Norwegian Institute for Water Research '), ('Norwegian University for Science and Technology', 'Norwegian University for Science and Technology'), ('Norwegian Computing Center', 'Norwegian Computing Center'), ('Grid-Arendal', 'Grid-Arendal'), ('Norwegian Institute for Nature Research', 'Norwegian Institute for Nature Research'), ('Institute for Marine Research', 'Institute for Marine Research'), ('Spectrofly Aps', 'Spectrofly Aps'), ('Andøya Space Center', 'Andøya Space Center'), ('UNINETT/Sigma2', 'UNINETT/Sigma2'), ('Weag Solutions AS', 'Weag Solutions AS'), ('Miljødirektoratet', 'Miljødirektoratet'), ('Uni of Southern Denmark', 'Uni of Southern Denmark'), ('University of Exeter', 'University of Exeter'), ('University of Tromsø', 'University of Tromsø'), ('The Research Council of Norway', 'The Research Council of Norway'), ('SeaBee', 'SeaBee'), ('Other', 'Other')], max_length=300, verbose_name='Organisation you represent? ')),
                ('organisation_other', models.CharField(blank=True, max_length=300, null=True, verbose_name='Please specify your organisation')),
                ('pesonal_profile', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to the personal profile page')),
                ('agreement', models.BooleanField(verbose_name='By clicking here, I state that I have read and understood the terms and conditions.')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profile',
            },
        ),
        migrations.CreateModel(
            name='Historicaluser_profile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=300, verbose_name='First name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last name')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('undisclosed ', 'Undisclosed')], max_length=300, null=True, verbose_name='Gender')),
                ('organisation', models.CharField(choices=[('Norwegian Institute for Water Research ', 'Norwegian Institute for Water Research '), ('Norwegian University for Science and Technology', 'Norwegian University for Science and Technology'), ('Norwegian Computing Center', 'Norwegian Computing Center'), ('Grid-Arendal', 'Grid-Arendal'), ('Norwegian Institute for Nature Research', 'Norwegian Institute for Nature Research'), ('Institute for Marine Research', 'Institute for Marine Research'), ('Spectrofly Aps', 'Spectrofly Aps'), ('Andøya Space Center', 'Andøya Space Center'), ('UNINETT/Sigma2', 'UNINETT/Sigma2'), ('Weag Solutions AS', 'Weag Solutions AS'), ('Miljødirektoratet', 'Miljødirektoratet'), ('Uni of Southern Denmark', 'Uni of Southern Denmark'), ('University of Exeter', 'University of Exeter'), ('University of Tromsø', 'University of Tromsø'), ('The Research Council of Norway', 'The Research Council of Norway'), ('SeaBee', 'SeaBee'), ('Other', 'Other')], max_length=300, verbose_name='Organisation you represent? ')),
                ('organisation_other', models.CharField(blank=True, max_length=300, null=True, verbose_name='Please specify your organisation')),
                ('pesonal_profile', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link to the personal profile page')),
                ('agreement', models.BooleanField(verbose_name='By clicking here, I state that I have read and understood the terms and conditions.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user_profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
