# Generated by Django 3.2 on 2023-01-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalddc_main',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flight_mission_guid', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dronelogbook Id')),
                ('flight_mission_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Flight Mission Name')),
                ('drone_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Drone Type')),
                ('image_overlap', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Overlap')),
                ('cdom', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cdom– ug/l Quinine sulphate (0-500 -upper figure is a maximum guess and should be adjustable)')),
                ('turbidity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Turbidity- FNU (0-100)')),
                ('Salinity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salinity- PSU (0-40)')),
                ('water_temperature', models.PositiveIntegerField(blank=True, null=True, verbose_name='Water Temperature (1.7<sup> o</sup>C – 35<sup> o</sup>C)')),
                ('secchi_depth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Secchi Depth (metres)')),
                ('sensor_dates_last_calibration', models.DateField(blank=True, null=True, verbose_name='Dates of last calibration')),
                ('sensor_dates_last_maintenance', models.DateField(blank=True, null=True, verbose_name='Dates of last maintenance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.user_profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ddc_main',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ddc_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_mission_guid', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dronelogbook Id')),
                ('flight_mission_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Flight Mission Name')),
                ('drone_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Drone Type')),
                ('image_overlap', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Overlap')),
                ('cdom', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cdom– ug/l Quinine sulphate (0-500 -upper figure is a maximum guess and should be adjustable)')),
                ('turbidity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Turbidity- FNU (0-100)')),
                ('Salinity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salinity- PSU (0-40)')),
                ('water_temperature', models.PositiveIntegerField(blank=True, null=True, verbose_name='Water Temperature (1.7<sup> o</sup>C – 35<sup> o</sup>C)')),
                ('secchi_depth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Secchi Depth (metres)')),
                ('sensor_dates_last_calibration', models.DateField(blank=True, null=True, verbose_name='Dates of last calibration')),
                ('sensor_dates_last_maintenance', models.DateField(blank=True, null=True, verbose_name='Dates of last maintenance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddc_for_metadata', to='home.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Dronelogbook additinal parameter',
            },
        ),
    ]
