# Generated by Django 3.2 on 2023-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0002_auto_20230126_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddc_upload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Public Attachment ID'),
        ),
        migrations.AlterField(
            model_name='historicalddc_upload',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Public Attachment ID'),
        ),
    ]
