# Generated by Django 3.2 on 2023-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0002_ddc_main_historicalddc_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddc_main',
            options={'verbose_name_plural': 'Dronelogbook additional parameter'},
        ),
        migrations.RenameField(
            model_name='ddc_main',
            old_name='Salinity',
            new_name='salinity',
        ),
        migrations.RenameField(
            model_name='historicalddc_main',
            old_name='Salinity',
            new_name='salinity',
        ),
        migrations.AlterField(
            model_name='ddc_main',
            name='water_temperature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Water Temperature (1.7C – 35C)'),
        ),
        migrations.AlterField(
            model_name='historicalddc_main',
            name='water_temperature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Water Temperature (1.7C – 35C)'),
        ),
    ]
