# Generated by Django 3.2 on 2023-01-26 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dmc', '0004_auto_20230126_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='ddc_upload',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 1, 26, 17, 45, 25, 989771, tzinfo=utc), storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Object Upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddc_upload',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Related Object's ID"),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='file',
            field=models.TextField(default=datetime.datetime(2023, 1, 26, 17, 45, 34, 710325, tzinfo=utc), max_length=100, verbose_name='Object Upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Related Object's ID"),
        ),
    ]
