# Generated by Django 3.2 on 2023-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0004_auto_20230119_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddc_main',
            name='flight_mission_guid',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Dronelogbook Id'),
        ),
        migrations.AlterField(
            model_name='historicalddc_main',
            name='flight_mission_guid',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Dronelogbook Id'),
        ),
    ]
