# Generated by Django 3.2 on 2023-01-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0005_auto_20230126_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddc_upload',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalddc_upload',
            name='content_type',
        ),
    ]
