# Generated by Django 3.2 on 2023-01-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0007_auto_20230126_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddc_upload',
            old_name='file',
            new_name='mosaiced_image',
        ),
        migrations.RenameField(
            model_name='historicalddc_upload',
            old_name='file',
            new_name='mosaiced_image',
        ),
    ]
