# Generated by Django 3.2 on 2023-01-27 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0008_auto_20230126_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='mosaiced_image2',
            field=models.FileField(default=datetime.datetime(2023, 1, 27, 11, 14, 53, 813819, tzinfo=utc), storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Object Upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='mosaiced_image2',
            field=models.TextField(default=datetime.datetime(2023, 1, 27, 11, 14, 58, 221508, tzinfo=utc), max_length=100, verbose_name='Object Upload'),
            preserve_default=False,
        ),
    ]
