# Generated by Django 3.2 on 2023-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0008_alter_ddc_upload_mosaiced_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='flight_mission_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Flight Mission Name'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='flight_mission_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Flight Mission Name'),
        ),
    ]
