# Generated by Django 3.2 on 2023-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0009_auto_20230127_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='flight_mission_guid',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Dronelogbook Id'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='flight_mission_guid',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Dronelogbook Id'),
        ),
    ]
