# Generated by Django 3.2 on 2023-02-17 17:22

from django.db import migrations, models
import django_minio_backend.models
import dmc.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0009_auto_20230217_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddc_upload',
            name='mosaiced_image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'gcp'}), verbose_name='Upload single mosaiced file'),
        ),
    ]
