# Generated by Django 3.2 on 2023-02-17 17:40

from django.db import migrations, models
import django_minio_backend.models
import dmc.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0010_alter_ddc_upload_mosaiced_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddc_upload',
            name='dronePath',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'drone_path'}), verbose_name='Upload drone path file as .kml'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='ground_control_point',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'gcp'}), verbose_name='Upload ground control point as .csv'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='ground_truth_point',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'ground_truth'}), verbose_name='Upload ground truth point as .csv'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='mosaiced_image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'orthomosaic'}), verbose_name='Upload single mosaiced file'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='row_image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'raw_images'}), verbose_name='Upload raw images a single .zip file'),
        ),
    ]
