# Generated by Django 3.2 on 2023-02-17 17:44

from django.db import migrations, models
import django_minio_backend.models
import dmc.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0011_auto_20230217_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='other',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(dmc.models.get_upload_path, *(), **{'folder': 'other'}), verbose_name='Upload drone path file as .kml'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='other',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload drone path file as .kml'),
        ),
    ]
