# Generated by Django 3.2 on 2023-01-30 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0012_auto_20230127_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddc_upload',
            name='mosaiced_image2',
        ),
        migrations.RemoveField(
            model_name='historicalddc_upload',
            name='mosaiced_image2',
        ),
        migrations.AddField(
            model_name='ddc_upload',
            name='row_image',
            field=models.FileField(default=datetime.datetime(2023, 1, 30, 14, 7, 56, 760035, tzinfo=utc), storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload raw images a single .zip file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='row_image',
            field=models.TextField(default=datetime.datetime(2023, 1, 30, 14, 8, 1, 719012, tzinfo=utc), max_length=100, verbose_name='Upload raw images a single .zip file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='mosaiced_image',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload single mosaiced file'),
        ),
        migrations.AlterField(
            model_name='historicalddc_upload',
            name='mosaiced_image',
            field=models.TextField(max_length=100, verbose_name='Upload single mosaiced file'),
        ),
    ]
