# Generated by Django 3.2 on 2023-01-30 14:13

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0013_auto_20230130_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='dronePath',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload drone path file as .kml'),
        ),
        migrations.AddField(
            model_name='ddc_upload',
            name='ground_control_point',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload ground control point as .csv'),
        ),
        migrations.AddField(
            model_name='ddc_upload',
            name='ground_truth_point',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload ground truth point as .csv'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='dronePath',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload drone path file as .kml'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='ground_control_point',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload ground control point as .csv'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='ground_truth_point',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload ground truth point as .csv'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='mosaiced_image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload single mosaiced file'),
        ),
        migrations.AlterField(
            model_name='ddc_upload',
            name='row_image',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='dmc'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Upload raw images a single .zip file'),
        ),
        migrations.AlterField(
            model_name='historicalddc_upload',
            name='mosaiced_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload single mosaiced file'),
        ),
        migrations.AlterField(
            model_name='historicalddc_upload',
            name='row_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload raw images a single .zip file'),
        ),
    ]
