# Generated by Django 3.2 on 2023-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0014_auto_20230130_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldmc_main',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldmc_main',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldrone_info_list',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsensor_info_list',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='dmc_main',
        ),
        migrations.DeleteModel(
            name='drone_info_list',
        ),
        migrations.DeleteModel(
            name='Historicaldmc_main',
        ),
        migrations.DeleteModel(
            name='Historicaldrone_info_list',
        ),
        migrations.DeleteModel(
            name='Historicalsensor_info_list',
        ),
        migrations.DeleteModel(
            name='sensor_info_list',
        ),
    ]
